# This workflow will run robot code on browserstack and automatically post the results on Zephyr

name: 'BrowserStack CloudTest'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu-job:
    name: 'BrowserStack Test'
    runs-on: ubuntu-latest  # Can be self-hosted runner also
    steps:
      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      - name: 'Checkout the repository'
        uses: actions/checkout@v2
     
        

